services:
  db:
    image: postgis/postgis:15-3.3
    ports:
      - "5432:5432"
    volumes:
      - /private/var/lib/postgresql:/var/lib/postgresql
    env_file:
      - .env

  web:
    build: .
    command: >
      sh -c "apt update &&
             apt install gdal-bin libpq5 -y &&
             python manage.py wait_for_db &&
             python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
